### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

### ISSUE THREAD

**Issue by dglancy** [tomkadwill/atom-rails-debugger#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-rails-debugger](https://github.com/tomkadwill/atom-rails-debugger) package, v0.2.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

```
At /Users/dglancy/.atom/packages/atom-rails-debugger/lib/atom-rails-debugger.coffee:33

TypeError: Cannot read property 'getCursorBufferPosition' of undefined
    at Object.module.exports.AtomRailsDebugger.toggle (/Users/dglancy/.atom/packages/atom-rails-debugger/lib/atom-rails-debugger.coffee:33:17)
    at atom-workspace.subscriptions.add.atom.commands.add.atom-rails-debugger:toggle (/Users/dglancy/.atom/packages/atom-rails-debugger/lib/atom-rails-debugger.coffee:19:94)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -4:09.6.0 core:close (atom-text-editor.editor.is-focused)
     -4:08.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -4:02.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:58.6.0 core:close (atom-text-editor.editor.is-focused)
     -3:57.7.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -3:53.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:51.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:50.4.0 core:close (atom-text-editor.editor.is-focused)
     -3:49.8.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -3:46.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:57.2.0 fuzzy-finder:toggle-file-finder (button.btn.icon.enablement.icon-playback-play)
  2x -1:53.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -1:51.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -0:34.4.0 atom-rails-debugger:toggle (atom-text-editor.editor.is-focused)
     -0:04.5.0 ruby-test:toggle (div.package-detail.panels-item)
     -0:00.9.0 atom-rails-debugger:toggle (div.package-detail.panels-item)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "language-toml",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-make",
      "language-mustache",
      "language-perl",
      "language-php",
      "language-python"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-rails-debugger, v0.2.0
minimap, v4.19.0
pigments, v0.23.1
project-manager, v2.7.6
rails-transporter, v1.6.5
ruby-block, v0.3.5
ruby-test, v0.9.17

# Dev
No dev packages
```

**Comment by tomkadwill** [comment]
Hi @dglancy, thanks for reporting this bug. The plugin is still very much in development at the moment so there will be lots of bugs and unexpected behaviour! I will try to look at this soon
